[package]
name = "program"
version = "0.1.0"
description = "Lock-n-Roll OTC Market"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lock_n_roll"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token"] }
proc-macro2 = { version = "1", features = ["span-locations"] }